// <auto-generated />
using System;
using ASP.NETCoreRestAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NETCoreRestAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NETCoreRestAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UpdatedDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateOnly(2025, 7, 29),
                            Details = "A luxurious villa with a private pool and garden.",
                            ImageUrl = "https://example.com/images/royal-villa.jpg",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Rate = 200.0,
                            Sqft = 1500,
                            UpdatedDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateOnly(2025, 7, 29),
                            Details = "A beautiful villa located right on the beach.",
                            ImageUrl = "https://example.com/images/beachfront-villa.jpg",
                            Name = "Beachfront Villa",
                            Occupancy = 6,
                            Rate = 300.0,
                            Sqft = 1800,
                            UpdatedDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateOnly(2025, 7, 29),
                            Details = "A serene villa with stunning mountain views.",
                            ImageUrl = "https://example.com/images/mountain-view-villa.jpg",
                            Name = "Mountain View Villa",
                            Occupancy = 5,
                            Rate = 250.0,
                            Sqft = 1600,
                            UpdatedDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateOnly(2025, 7, 29),
                            Details = "A charming villa surrounded by lush gardens.",
                            ImageUrl = "https://example.com/images/garden-villa.jpg",
                            Name = "Garden Villa",
                            Occupancy = 3,
                            Rate = 180.0,
                            Sqft = 1400,
                            UpdatedDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateOnly(2025, 7, 29),
                            Details = "A modern villa located in the heart of the city.",
                            ImageUrl = "https://example.com/images/city-center-villa.jpg",
                            Name = "City Center Villa",
                            Occupancy = 2,
                            Rate = 220.0,
                            Sqft = 1300,
                            UpdatedDate = new DateOnly(1, 1, 1)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
